# Generated by Django 5.0.1 on 2025-12-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='starter_code',
            field=models.TextField(default='# Write your code here\n', help_text='Initial code template for the user'),
        ),
    ]
