"""
Django settings for Gamified Python Learner AI project.

Generated by 'django-admin startproject' using Django 5.0.1.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (only in development)
env_path = os.path.join(BASE_DIR, '.env')
if os.path.exists(env_path):
    load_dotenv(env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-change-this')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    # Django Built-in Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party Apps
    'corsheaders',
    
    # Project Apps
    'apps.authentication',
    'apps.learning',
    'apps.coding',
    'apps.gamification',
    'apps.ai_tutor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS support
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# For development: SQLite
# For production: PostgreSQL (uncomment and configure)

# Database configuration
import dj_database_url

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Production: Use DATABASE_URL from Render
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Development: Use SQLite or PostgreSQL
    DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3')
    
    if DB_ENGINE == 'django.db.backends.sqlite3':
        DATABASES = {
            'default': {
                'ENGINE': DB_ENGINE,
                'NAME': BASE_DIR / os.getenv('DB_NAME', 'db.sqlite3'),
            }
        }
    else:
        # PostgreSQL Configuration
        DATABASES = {
            'default': {
                'ENGINE': DB_ENGINE,
                'NAME': os.getenv('DB_NAME'),
                'USER': os.getenv('DB_USER'),
                'PASSWORD': os.getenv('DB_PASSWORD'),
                'HOST': os.getenv('DB_HOST', 'localhost'),
                'PORT': os.getenv('DB_PORT', '5432'),
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========================================
# Custom Settings for Python Learner AI
# ========================================

# Google Gemini AI Configuration
# Read API key from environment variable first, then from file as fallback
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
if not GEMINI_API_KEY:
    # Fallback: try to read from file
    GEMINI_API_KEY_FILE = os.path.join(BASE_DIR, 'Gemini_api_key.txt')
    if os.path.exists(GEMINI_API_KEY_FILE):
        with open(GEMINI_API_KEY_FILE, 'r', encoding='utf-8') as f:
            GEMINI_API_KEY = f.read().strip()
    if not GEMINI_API_KEY:
        raise ValueError(
            "GEMINI_API_KEY not found. Please set GEMINI_API_KEY environment variable "
            "or create Gemini_api_key.txt file with your API key."
        )

# Gemini Model Configuration
# Read model name from environment variable, default to 'gemini-2.0-flash-exp'
GEMINI_MODEL = os.getenv('GEMINI_MODEL', 'gemini-2.0-flash-exp')

# CORS Settings (for API access)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Authentication Settings
AUTHENTICATION_BACKENDS = [
    'apps.authentication.backends.EmailOrUsernameBackend',  # Custom backend for email/username login
    'django.contrib.auth.backends.ModelBackend',  # Default backend (fallback)
]
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Session Settings
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 1 week

# Email Configuration (for password reset)
# Supports multiple email providers: Brevo (HTTP API or SMTP), Gmail, SendGrid, etc.
# Read from environment variables first, then from file as fallback
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_PROVIDER = os.getenv('EMAIL_PROVIDER', 'brevo').lower()

# Brevo API Key (for HTTP API - preferred over SMTP)
BREVO_API_KEY = os.getenv('BREVO_API_KEY', '')
# If not in environment, try to read from EMAIL_HOST_PASSWORD (for backward compatibility)
if not BREVO_API_KEY and EMAIL_HOST_PASSWORD:
    # Check if EMAIL_HOST_PASSWORD looks like an API key (starts with 'xsmtpsib-')
    if EMAIL_HOST_PASSWORD.startswith('xsmtpsib-'):
        BREVO_API_KEY = EMAIL_HOST_PASSWORD

# If not in environment variables, try to read from file
if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    EMAIL_CREDENTIALS_FILE = os.path.join(BASE_DIR, 'Email_credentials.txt')
    if os.path.exists(EMAIL_CREDENTIALS_FILE):
        try:
            with open(EMAIL_CREDENTIALS_FILE, 'r', encoding='utf-8') as f:
                lines = [line.strip() for line in f.readlines() if line.strip() and not line.strip().startswith('#')]
                # Format: KEY=VALUE (one per line)
                email_config = {}
                for line in lines:
                    if '=' in line:
                        key, value = line.split('=', 1)
                        email_config[key.strip()] = value.strip()
                
                if not EMAIL_HOST_USER:
                    EMAIL_HOST_USER = email_config.get('EMAIL_HOST_USER', '')
                if not EMAIL_HOST_PASSWORD:
                    EMAIL_HOST_PASSWORD = email_config.get('EMAIL_HOST_PASSWORD', '')
                if email_config.get('EMAIL_PROVIDER') and not EMAIL_PROVIDER:
                    EMAIL_PROVIDER = email_config.get('EMAIL_PROVIDER', 'brevo').lower()
        except Exception as e:
            import logging
            logger = logging.getLogger(__name__)
            logger.warning(f"Error reading Email_credentials.txt: {e}")

# Set default provider if not specified
if not EMAIL_PROVIDER:
    EMAIL_PROVIDER = 'brevo'

# Check if email is configured
import logging
logger = logging.getLogger(__name__)

# Set DEFAULT_FROM_EMAIL
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'pythonlearnerai@gmail.com')
EMAIL_FROM_NAME = os.getenv('EMAIL_FROM_NAME', 'Python Learner AI')

# Configure email backend based on provider
if EMAIL_PROVIDER == 'brevo' and BREVO_API_KEY:
    # Use Brevo HTTP API (preferred - more reliable than SMTP)
    EMAIL_BACKEND = 'apps.authentication.brevo_api_backend.BrevoAPIEmailBackend'
    logger.info("Using Brevo HTTP API backend for email sending")
elif EMAIL_PROVIDER == 'brevo' and (EMAIL_HOST_USER and EMAIL_HOST_PASSWORD):
    # Fallback to SMTP if API key not available
    EMAIL_BACKEND = 'apps.authentication.email_backend.TimeoutSMTPEmailBackend'
    EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', 30))
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp-relay.brevo.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    logger.info("Using Brevo SMTP backend (API key not found, using SMTP credentials)")
elif not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    # No credentials configured
    if DEBUG:
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
        logger.warning("Email credentials not set - using console backend for development")
    else:
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
        logger.error("Email credentials not set in production! Emails will fail!")
else:
    # Other providers (SendGrid, Mailgun, Gmail, etc.) - use SMTP
    EMAIL_BACKEND = 'apps.authentication.email_backend.TimeoutSMTPEmailBackend'
    EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', 30))
    
    # Configure based on email provider
    if EMAIL_PROVIDER == 'brevo':
        EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp-relay.brevo.com')
        EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
        EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    elif EMAIL_PROVIDER == 'sendgrid':
        # SendGrid - Free: 100 emails/day
        EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.sendgrid.net')
        EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
        EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
        # SendGrid uses 'apikey' as username
        if EMAIL_HOST_USER and not EMAIL_HOST_USER.startswith('apikey'):
            EMAIL_HOST_USER = 'apikey'
    elif EMAIL_PROVIDER == 'mailgun':
        # Mailgun - Free: 100 emails/month
        EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.mailgun.org')
        EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
        EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    else:
        # Default: Gmail or custom SMTP
        EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
        EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
        EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    

# Code Execution Security Settings
CODE_EXECUTION_TIMEOUT = 10  # seconds
CODE_EXECUTION_MAX_MEMORY = 128 * 1024 * 1024  # 128MB

# Custom User Model
AUTH_USER_MODEL = 'authentication.User'

# Gamification Settings
XP_PER_EXERCISE = 50
XP_PER_LESSON = 100
XP_FOR_LEVEL_UP_BASE = 1000  # Level 1 -> 2 requires 1000 XP
XP_MULTIPLIER_PER_LEVEL = 1.5  # Each level requires 1.5x more XP

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.authentication': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'apps.authentication.email_backend': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Log email configuration at startup
import logging
logger = logging.getLogger(__name__)
logger.info("=" * 60)
logger.info("EMAIL CONFIGURATION:")
logger.info(f"  EMAIL_PROVIDER: {EMAIL_PROVIDER}")
if EMAIL_PROVIDER == 'brevo':
    logger.info(f"  BREVO_API_KEY: {'SET (hidden)' if BREVO_API_KEY else 'NOT SET'}")
    logger.info(f"  EMAIL_HOST_USER: {EMAIL_HOST_USER if EMAIL_HOST_USER else 'NOT SET'}")
    logger.info(f"  EMAIL_HOST_PASSWORD: {'SET (hidden)' if EMAIL_HOST_PASSWORD else 'NOT SET'}")
else:
    logger.info(f"  EMAIL_HOST_USER: {EMAIL_HOST_USER if EMAIL_HOST_USER else 'NOT SET'}")
    logger.info(f"  EMAIL_HOST_PASSWORD: {'SET (hidden)' if EMAIL_HOST_PASSWORD else 'NOT SET'}")
logger.info(f"  EMAIL_HOST: {getattr(globals(), 'EMAIL_HOST', 'NOT SET')}")
logger.info(f"  EMAIL_PORT: {getattr(globals(), 'EMAIL_PORT', 'NOT SET')}")
logger.info(f"  EMAIL_USE_TLS: {getattr(globals(), 'EMAIL_USE_TLS', 'NOT SET')}")
logger.info(f"  DEFAULT_FROM_EMAIL: {DEFAULT_FROM_EMAIL}")
logger.info(f"  EMAIL_BACKEND: {EMAIL_BACKEND}")
logger.info("=" * 60)
