# Generated by Django 5.0.1 on 2025-12-02 13:25

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Badge Name')),
                ('description', models.TextField(help_text='What this badge represents', verbose_name='Description')),
                ('icon', models.CharField(help_text='Emoji or icon class', max_length=50, verbose_name='Icon')),
                ('badge_type', models.CharField(choices=[('achievement', 'Achievement'), ('milestone', 'Milestone'), ('special', 'Special')], default='achievement', max_length=20, verbose_name='Badge Type')),
                ('criteria', models.JSONField(help_text='JSON object defining how to earn this badge', verbose_name='Criteria')),
                ('xp_reward', models.IntegerField(default=0, help_text='XP awarded when earning this badge', verbose_name='XP Reward')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'db_table': 'badges',
                'ordering': ['badge_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('challenge_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20, verbose_name='Challenge Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('target_metric', models.CharField(choices=[('exercises_solved', 'Exercises Solved'), ('lessons_completed', 'Lessons Completed'), ('xp_earned', 'XP Earned'), ('code_submissions', 'Code Submissions')], max_length=50, verbose_name='Target Metric')),
                ('target_value', models.IntegerField(help_text='Goal to achieve', verbose_name='Target Value')),
                ('xp_reward', models.IntegerField(default=100, verbose_name='XP Reward')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'db_table': 'challenges',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['challenge_type', 'is_active', 'start_date'], name='challenges_challen_4e2088_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, help_text='Current consecutive days of activity', verbose_name='Current Streak')),
                ('longest_streak', models.IntegerField(default=0, help_text='Longest streak ever achieved', verbose_name='Longest Streak')),
                ('last_activity_date', models.DateField(default=datetime.date.today, verbose_name='Last Activity Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Daily Streak',
                'verbose_name_plural': 'Daily Streaks',
                'db_table': 'daily_streaks',
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests', to=settings.AUTH_USER_MODEL, verbose_name='Friend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Friendship',
                'verbose_name_plural': 'Friendships',
                'db_table': 'friendships',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='friendships_user_id_451268_idx'), models.Index(fields=['friend', 'status'], name='friendships_friend__713609_idx')],
                'unique_together': {('user', 'friend')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Earned At')),
                ('progress', models.IntegerField(default=100, help_text='Progress percentage (0-100)', verbose_name='Progress')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='gamification.badge', verbose_name='Badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'db_table': 'user_badges',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', '-earned_at'], name='user_badges_user_id_4dadab_idx')],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, help_text='Current progress toward goal', verbose_name='Progress')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started At')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gamification.challenge', verbose_name='Challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Challenge',
                'verbose_name_plural': 'User Challenges',
                'db_table': 'user_challenges',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'completed'], name='user_challe_user_id_0d3ad0_idx')],
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
